menu:
    # Home: /
    Archive: /archives/
    # Tags: /tags/
    # Categories: /categories/
    About: /about/
    # Rss: /atom.xml
    Search: /search/

favicon: /favicon.ico
logo: /avatar.jpg

# Comment

gitalk:
  enable: true
  owner: allenfrostline
  repo: Comments-on-Whiteboard
  client_id: 8f880a91b82796d2ce14
  client_secret: dc2c450f9bd7fba631ce51de266a12684a729e89

# Analytics
ga: UA-93356635-1

# Adsense
google_adsense:
  page_level_ads: false
  unit_level_ads: false
  data_ad_client: ca-pub-8935595858652656
  data_ad_slot: 6325921777

# Copyright Infomation
# post_copyright:
#   license: CC BY-NC-SA 4.0
#   license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/